package nlp

var CorpusIngredients = []string{" can cream of chicken soup ",
	" cream of mushroom soup ",
	" graham cracker crumbs ",
	" salt and black pepper ",
	" heavy whipping cream ",
	" limnophila aromatica ",
	" vegetable shortening ",
	" vietnamese coriander ",
	" worcestershire sauce ",
	" apple cider vinegar ",
	" confectioners sugar ",
	" jerusalem artichoke ",
	" new zealand spinach ",
	" bolivian coriander ",
	" grains of paradise ",
	" houttuynia cordata ",
	" white wine vinegar ",
	" black peppercorns ",
	" cream of mushroom ",
	" east asian pepper ",
	" green bell pepper ",
	" italian seasoning ",
	" mozzarella cheese ",
	" pumpkin pie spice ",
	" purple mangosteen ",
	" red pepper flakes ",
	" vanilla ice cream ",
	" alligator pepper ",
	" artichoke hearts ",
	" balsamic vinegar ",
	" black peppercorn ",
	" brazilian pepper ",
	" broccoli florets ",
	" butternut squash ",
	" greater galangal ",
	" green peppercorn ",
	" hot pepper sauce ",
	" jalapeno chilies ",
	" pomegranate seed ",
	" red wine vinegar ",
	" spaghetti squash ",
	" tasmanian pepper ",
	" white peppercorn ",
	" american cheese ",
	" aromatic ginger ",
	" brussels sprout ",
	" bunium persicum ",
	" cherry tomatoes ",
	" chicken breasts ",
	" cilantro leaves ",
	" cream of tartar ",
	" evaporated milk ",
	" flour tortillas ",
	" graham crackers ",
	" grains of selim ",
	" herbs and spice ",
	" indian bay leaf ",
	" lasagna noodles ",
	" lesser galangal ",
	" mzarella cheese ",
	" parmesan cheese ",
	" peruvian pepper ",
	" pineapple juice ",
	" red bell pepper ",
	" salt and pepper ",
	" vegetable broth ",
	" vegetable stock ",
	" water chestnuts ",
	" yellow cake mix ",
	" yellow cornmeal ",
	" alfalfa sprout ",
	" almond extract ",
	" barbecue sauce ",
	" black cardamom ",
	" black-eyed pea ",
	" cayenne pepper ",
	" cheddar cheese ",
	" chicken breast ",
	" chicken thighs ",
	" coriander leaf ",
	" coriander seed ",
	" corn tortillas ",
	" cottage cheese ",
	" dark chocolate ",
	" dry white wine ",
	" hubbard squash ",
	" nigella sativa ",
	" parsley flakes ",
	" parsley leaves ",
	" powdered sugar ",
	" ricotta cheese ",
	" seasoning salt ",
	" sichuan pepper ",
	" smoked paprika ",
	" sweet potatoes ",
	" tabasco pepper ",
	" teriyaki sauce ",
	" voatsiperifery ",
	" water chestnut ",
	" whipping cream ",
	" baking powder ",
	" banana squash ",
	" black mustard ",
	" borlotti bean ",
	" brown mustard ",
	" celery powder ",
	" chicken broth ",
	" chicken stock ",
	" cider vinegar ",
	" collard green ",
	" cooking spray ",
	" dijon mustard ",
	" garlic chives ",
	" garlic powder ",
	" green chilies ",
	" green peppers ",
	" half and half ",
	" juniper berry ",
	" lemon verbena ",
	" litsea cubeba ",
	" mustard green ",
	" peanut butter ",
	" plum tomatoes ",
	" potato starch ",
	" tabasco sauce ",
	" vegetable oil ",
	" whipped cream ",
	" white mustard ",
	" white vinegar ",
	" acorn squash ",
	" almond flour ",
	" baby spinach ",
	" basil leaves ",
	" black olives ",
	" black pepper ",
	" blackcurrant ",
	" blood orange ",
	" bread crumbs ",
	" broccoflower ",
	" canary melon ",
	" chicken soup ",
	" chili pepper ",
	" chili powder ",
	" coconut milk ",
	" corn kernels ",
	" cream cheese ",
	" curry powder ",
	" dry red wine ",
	" garam masala ",
	" green onions ",
	" green pepper ",
	" kidney beans ",
	" lemon myrtle ",
	" mango-ginger ",
	" marshmallows ",
	" onion powder ",
	" orange juice ",
	" passionfruit ",
	" purple onion ",
	" rice vinegar ",
	" sarsaparilla ",
	" sesame seeds ",
	" strawberries ",
	" sweet potato ",
	" swiss cheese ",
	" thyme leaves ",
	" tomato juice ",
	" tomato paste ",
	" tomato sauce ",
	" walnut flour ",
	" white pepper ",
	" white radish ",
	" yellow onion ",
	" almond meal ",
	" almond milk ",
	" apple juice ",
	" baking soda ",
	" bean sprout ",
	" bell pepper ",
	" black beans ",
	" blue cheese ",
	" blueberries ",
	" boysenberry ",
	" bread flour ",
	" breadcrumbs ",
	" broad beans ",
	" brown sugar ",
	" cauliflower ",
	" celery seed ",
	" chili sauce ",
	" coconut oil ",
	" cooking oil ",
	" corn starch ",
	" cranberries ",
	" dragonfruit ",
	" dry mustard ",
	" egg noodles ",
	" feta cheese ",
	" garlic salt ",
	" goat cheese ",
	" green beans ",
	" green onion ",
	" heavy cream ",
	" horseradish ",
	" huckleberry ",
	" kidney bean ",
	" lemon grass ",
	" lemon juice ",
	" long pepper ",
	" maple syrup ",
	" mint leaves ",
	" orange peel ",
	" pomegranate ",
	" raspberries ",
	" red peppers ",
	" rice noodle ",
	" runner bean ",
	" salal berry ",
	" sweet onion ",
	" tomato soup ",
	" white onion ",
	" applesauce ",
	" asafoetida ",
	" azuki bean ",
	" bay leaves ",
	" beef broth ",
	" beef stock ",
	" black bean ",
	" blackberry ",
	" breadfruit ",
	" brown rice ",
	" buttermilk ",
	" canola oil ",
	" cantaloupe ",
	" clementine ",
	" cloudberry ",
	" corn flour ",
	" corn salad ",
	" corn syrup ",
	" cornstarch ",
	" cumin seed ",
	" curry leaf ",
	" dried lime ",
	" dry sherry ",
	" elderberry ",
	" fiddlehead ",
	" fingerroot ",
	" fish sauce ",
	" gem squash ",
	" goji berry ",
	" gooseberry ",
	" grapefruit ",
	" green bean ",
	" hoja santa ",
	" holy basil ",
	" kiwi fruit ",
	" lemon balm ",
	" lemon peel ",
	" lemon rind ",
	" lime juice ",
	" matzo meal ",
	" mayonnaise ",
	" peanut oil ",
	" peppermint ",
	" pinto bean ",
	" poppy seed ",
	" prosciutto ",
	" red pepper ",
	" redcurrant ",
	" rice flour ",
	" rock melon ",
	" sesame oil ",
	" shortening ",
	" sour cream ",
	" star anise ",
	" star fruit ",
	" strawberry ",
	" thai basil ",
	" tonka bean ",
	" topinambur ",
	" ugli fruit ",
	" watercress ",
	" watermelon ",
	" white rice ",
	" white wine ",
	" artichoke ",
	" asparagus ",
	" aubergine ",
	" blueberry ",
	" calabrese ",
	" chamomile ",
	" cherimoya ",
	" chickpeas ",
	" chocolate ",
	" cool whip ",
	" coriander ",
	" courgette ",
	" cranberry ",
	" dill seed ",
	" dill weed ",
	" fenugreek ",
	" hamburger ",
	" hazelnuts ",
	" hot sauce ",
	" jackfruit ",
	" kinh gioi ",
	" lima bean ",
	" liquorice ",
	" mandarine ",
	" mangetout ",
	" margarine ",
	" mung bean ",
	" mushrooms ",
	" navy bean ",
	" nectarine ",
	" oat flour ",
	" olive oil ",
	" patty pan ",
	" persimmon ",
	" pie crust ",
	" pie shell ",
	" pine nuts ",
	" pineapple ",
	" radicchio ",
	" raspberry ",
	" red onion ",
	" salad oil ",
	" sassafras ",
	" scallions ",
	" skim milk ",
	" soy sauce ",
	" spaghetti ",
	" tamarillo ",
	" tangerine ",
	" allspice ",
	" amaranth ",
	" angelica ",
	" bay leaf ",
	" bilberry ",
	" bok choy ",
	" broccoli ",
	" cardamom ",
	" celeriac ",
	" cherries ",
	" chickpea ",
	" cilantro ",
	" cinnamon ",
	" cornmeal ",
	" crabmeat ",
	" cucumber ",
	" culantro ",
	" delicata ",
	" dressing ",
	" eggplant ",
	" habanero ",
	" honeydew ",
	" jalapeno ",
	" kohlrabi ",
	" korarima ",
	" lavender ",
	" marjoram ",
	" molasses ",
	" mulberry ",
	" mushroom ",
	" physalis ",
	" potatoes ",
	" rambutan ",
	" red wine ",
	" rosemary ",
	" rutabaga ",
	" scallion ",
	" semolina ",
	" shallots ",
	" snap pea ",
	" soy bean ",
	" tamarind ",
	" tarragon ",
	" tomatoes ",
	" turmeric ",
	" woodruff ",
	" zucchini ",
	" almonds ",
	" amchoor ",
	" apricot ",
	" arugula ",
	" avocado ",
	" bananas ",
	" cabbage ",
	" camphor ",
	" caraway ",
	" carrots ",
	" cashews ",
	" cayenne ",
	" charoli ",
	" chayote ",
	" chervil ",
	" chicken ",
	" coconut ",
	" currant ",
	" epazote ",
	" gelatin ",
	" ketchup ",
	" kumquat ",
	" lentils ",
	" lettuce ",
	" mitsuba ",
	" mugwort ",
	" mustard ",
	" nigella ",
	" njangsa ",
	" oatmeal ",
	" oranges ",
	" oregano ",
	" paprika ",
	" parsley ",
	" parsnip ",
	" peaches ",
	" peanuts ",
	" perilla ",
	" pumpkin ",
	" radhuni ",
	" raisins ",
	" rhubarb ",
	" saffron ",
	" satsuma ",
	" sausage ",
	" shallot ",
	" skirret ",
	" spinach ",
	" squash ",
	" tat soi ",
	" vanilla ",
	" vinegar ",
	" walnuts ",
	" zedoary ",
	" zereshk ",
	" ajwain ",
	" aonori ",
	" apples ",
	" banana ",
	" borage ",
	" brandy ",
	" butter ",
	" capers ",
	" carrot ",
	" cassia ",
	" catsup ",
	" celery ",
	" cheese ",
	" chenpi ",
	" cherry ",
	" chives ",
	" cicely ",
	" coffee ",
	" daikon ",
	" damson ",
	" durian ",
	" endive ",
	" feijoa ",
	" fennel ",
	" frisee ",
	" garlic ",
	" ginger ",
	" golpar ",
	" hyssop ",
	" jambul ",
	" jicama ",
	" jujube ",
	" legume ",
	" lemons ",
	" loquat ",
	" lovage ",
	" lychee ",
	" mahlab ",
	" mastic ",
	" nopale ",
	" nutmeg ",
	" olives ",
	" onions ",
	" orange ",
	" pamelo ",
	" papaya ",
	" pecans ",
	" pepper ",
	" pomelo ",
	" potato ",
	" quince ",
	" quinoa ",
	" radish ",
	" raisin ",
	" salmon ",
	" sansho ",
	" savory ",
	" sesame ",
	" shrimp ",
	" sorrel ",
	" tomato ",
	" tubers ",
	" turkey ",
	" turnip ",
	" wasabi ",
	" yogurt ",
	" anise ",
	" apple ",
	" bacon ",
	" basil ",
	" beans ",
	" beets ",
	" boldo ",
	" bread ",
	" chard ",
	" chile ",
	" clove ",
	" cocoa ",
	" cream ",
	" cress ",
	" cubeb ",
	" cumin ",
	" dates ",
	" flour ",
	" fruit ",
	" grape ",
	" guava ",
	" honey ",
	" jimbu ",
	" kokum ",
	" leek ",
	" leeks ",
	" lemon ",
	" mamey ",
	" mango ",
	" olive ",
	" onion ",
	" pasta ",
	" peach ",
	" pears ",
	" salad ",
	" salsa ",
	" sauce ",
	" shiso ",
	" spray ",
	" steak ",
	" sugar ",
	" sumac ",
	" thyme ",
	" uzazi ",
	" vodka ",
	" water ",
	" yeast ",
	" beef ",
	" beer ",
	" beet ",
	" corn ",
	" date ",
	" dill ",
	" eggs ",
	" flax ",
	" hemp ",
	" kale ",
	" lamb ",
	" lime ",
	" mace ",
	" milk ",
	" mint ",
	" nuts ",
	" oats ",
	" okra ",
	" pear ",
	" peas ",
	" plum ",
	" pork ",
	" rice ",
	" rose ",
	" sage ",
	" salt ",
	" soda ",
	" taro ",
	" thru ",
	" tofu ",
	" tuna ",
	" yuzu ",
	" zest ",
	" fig ",
	" ham ",
	" ice ",
	" nut ",
	" oil ",
	" pea ",
	" rue ",
	" yam "}

var CorpusMeasures = []string{" tablespoons ",
	" milliliter ",
	" tablespoon ",
	" teaspoons ",
	" teaspoon ",
	" canned ",
	" ounces ",
	" pounds ",
	" quarts ",
	" grams ",
	" ounce ",
	" pints ",
	" pound ",
	" quart ",
	" tbsps ",
	" cans ",
	" cups ",
	" gram ",
	" pint ",
	" tbsp ",
	" tsps ",
	" can ",
	" cup ",
	" tbl ",
	" tsp ",
	" ml ",
	" oz ",
	" c ",
	" g "}

var CorpusNumbers = []string{" 1/2 ",
	" 1/3 ",
	" 1/4 ",
	" 1/5 ",
	" 1/6 ",
	" 1/7 ",
	" 1/8 ",
	" 2/3 ",
	" 2/5 ",
	" 2/7 ",
	" 3/4 ",
	" 3/8 ",
	" 4/5 ",
	" 5/8 ",
	" 7/8 ",
	" 1 ",
	" 2 ",
	" 3 ",
	" 4 ",
	" 5 ",
	" 6 ",
	" 7 ",
	" 8 ",
	" 9 ",
	" 10 ",
	" 11 ",
	" 12 ",
	" 13 ",
	" 14 ",
	" 15 ",
	" 16 ",
	" 17 ",
	" 18 ",
	" 19 ",
	" 20 ",
	" ⅞ ",
	" ⅓ ",
	" ¼ ",
	" ¾ ",
	" ⅜ ",
	" ⅝ ",
	" ½ ",
	" ⅛ ",
	" ⅔ "}

var CorpusDirections = []string{" 1 ",
	" 10 ",
	" 15 ",
	" 2 ",
	" 25 ",
	" 375 ",
	" 6 ",
	" 8 ",
	" 9x13 ",
	" a ",
	" about ",
	" achieve ",
	" add ",
	" additional ",
	" an ",
	" and ",
	" arrange ",
	" assemble ",
	" bake ",
	" baking ",
	" basil ",
	" beef ",
	" before ",
	" boil ",
	" boiling ",
	" bottom ",
	" bowl ",
	" bring ",
	" brown ",
	" browned ",
	" butter ",
	" cheese ",
	" chopped ",
	" coconut ",
	" cold ",
	" color ",
	" combine ",
	" completely ",
	" cook ",
	" cookie ",
	" cooking ",
	" cool ",
	" corn ",
	" cover ",
	" covered ",
	" crushed ",
	" cup ",
	" cups ",
	" degrees ",
	" dish ",
	" distributed ",
	" does ",
	" drain ",
	" dutch ",
	" eggs ",
	" either ",
	" even ",
	" evenly ",
	" everything ",
	" f ",
	" fennel ",
	" foil ",
	" for ",
	" from ",
	" garlic ",
	" grab ",
	" ground ",
	" half ",
	" heat ",
	" hours ",
	" in ",
	" inch ",
	" into ",
	" is ",
	" italian ",
	" large ",
	" lasagna ",
	" layers ",
	" lengthwise ",
	" let ",
	" lightly ",
	" make ",
	" meat ",
	" medium ",
	" melted ",
	" minutes ",
	" mix ",
	" mixing ",
	" mixture ",
	" mozzarella ",
	" next ",
	" noodles ",
	" not ",
	" nutmeg ",
	" nuts ",
	" oats ",
	" occasionally ",
	" of ",
	" on ",
	" one ",
	" onion ",
	" or ",
	" oven ",
	" over ",
	" pans ",
	" parmesan ",
	" parsley ",
	" paste ",
	" pecans ",
	" pepper ",
	" pie ",
	" place ",
	" pot ",
	" pour ",
	" preheat ",
	" preheated ",
	" prevent ",
	" put ",
	" raisins ",
	" remaining ",
	" remove ",
	" repeat ",
	" ricotta ",
	" rinse ",
	" salt ",
	" salted ",
	" sauce ",
	" sausage ",
	" season ",
	" seasoning ",
	" seeds ",
	" serving ",
	" sheet ",
	" shell ",
	" simmer ",
	" slices ",
	" spoon ",
	" spray ",
	" spread ",
	" sprinkle ",
	" sticking ",
	" stir ",
	" stirring ",
	" sugar ",
	" sure ",
	" syrup ",
	" tablespoon ",
	" tablespoons ",
	" teaspoon ",
	" the ",
	" then ",
	" third ",
	" to ",
	" tomato ",
	" tomatoes ",
	" top ",
	" touch ",
	" transfer ",
	" until ",
	" water ",
	" well ",
	" with "}

var CorpusDirectionsNeg = []string{" a ",
	" all ",
	" also ",
	" amount ",
	" and ",
	" be ",
	" best ",
	" brand ",
	" butter ",
	" c ",
	" calcium ",
	" calories ",
	" carbohydrates ",
	" chip ",
	" chocolate ",
	" cholesterol ",
	" cookie ",
	" cookies. ",
	" costco ",
	" dessert ",
	" dinner ",
	" dough ",
	" ensure ",
	" equally ",
	" ever ",
	" excellent ",
	" fat ",
	" fiber ",
	" for ",
	" from ",
	" great! ",
	" have ",
	" i ",
	" images ",
	" iron ",
	" it's ",
	" just ",
	" kirkland ",
	" liking! ",
	" make ",
	" per ",
	" potassium ",
	" protein ",
	" recipe ",
	" recommend ",
	" results. ",
	" salted ",
	" saturated ",
	" serving ",
	" servings ",
	" sodium ",
	" tasting ",
	" text ",
	" that ",
	" the ",
	" then ",
	" these ",
	" tillamook ",
	" to ",
	" unsalted ",
	" use ",
	" used ",
	" vitamin ",
	" with ",
	" would ",
	" yield ",
	" your "}

type fractionNumber struct {
	FractionString string
	Value          float64
}

var CorpusFractionNumberMap = map[string]fractionNumber{
	"¼": fractionNumber{"1/4", 0.2500000000},
	"½": fractionNumber{"1/2", 0.5000000000},
	"¾": fractionNumber{"3/4", 0.7500000000},
	"⅓": fractionNumber{"1/3", 0.3333333333},
	"⅔": fractionNumber{"2/3", 0.6666666667},
	"⅛": fractionNumber{"1/8", 0.1250000000},
	"⅜": fractionNumber{"3/8", 0.3750000000},
	"⅝": fractionNumber{"5/8", 0.6250000000},
	"⅞": fractionNumber{"7/8", 0.8750000000},
}
